### ISSUE TITLE
Access of atlas data (including images, ROIs, & surfaces) by metadata or ROI query types

### ISSUE THREAD

**Issue by vijayiyer05** [FZJ-INM1-BDA/siibralab#18]
A core-functionality, carried over from Issue #1. 

Per @dickscheid, this should be demonstrated by displaying a a parcellation volume in: 
- a ortho-slice viewer (partly realized in https://github.com/FZJ-INM1-BDA/siibra-matlab/blob/70cbb9bc5b26128f433437b398819b487a177e97/step-by-step/02_maps_and_templates/02_access_brain_reference_templates.mlx)
- a surface mesh viewer (not yet avaible, similar to the [reference snippet](https://siibra-python.readthedocs.io/en/latest/examples/02_maps_and_templates/005_access_surface_maps.html#)

_Originally posted by @dickscheid in https://github.com/FZJ-INM1-BDA/siibra-matlab/issues/1#issuecomment-1087393491_

**Comment by dickscheid** [comment]
This is done meanwhile.
