### ISSUE TITLE
fetch Bug?

### ISSUE THREAD

**Issue by SBludau** [FZJ-INM1-BDA/siibralab#25]
HI,
I think there is another problem with fetching of labeled maps

`
>Fp1_labelled_map=region.getMask('mni')

Fp1_labelled_map = 

  LabelledRegionMap with properties:

            Name: "AreaFp1(FPole)left"
         Regions: [1×1 siibra.items.Region]
           Space: [1×1 siibra.items.Space]
    LabelIndices: [1×1 struct]

>Fp1_labelled_map.fetch()

Operator '==' is not supported for operands of type 'struct'.

Error in siibra.items.maps.LabelledRegionMap>@(i)regionNiftis(i).loadData()==obj.LabelIndices(i) (line 68)
                maskData = arrayfun(@(i) regionNiftis(i).loadData() == obj.LabelIndices(i), 1:numel(regionNiftis), 'UniformOutput',false);

Error in siibra.items.maps.LabelledRegionMap/fetch (line 68)
                maskData = arrayfun(@(i) regionNiftis(i).loadData() == obj.LabelIndices(i), 1:numel(regionNiftis), 'UniformOutput',false);
 `

**Comment by valentin-pinkau** [comment]
I think this should be fixed with the latest commit in #24
