### ISSUE TITLE
Code Style Matters

### ISSUE THREAD

**Issue by vijayiyer05** [FZJ-INM1-BDA/siibralab#6]
Umbrella issue for MATLAB code style matters and discussion

**Comment by vijayiyer05** [comment]
Suggest now is a good time to start using [package folders](https://www.mathworks.com/help/matlab/matlab_oop/scoping-classes-with-packages.html). 

Likely the root folder would itself be `+siibra`, so suggest to consider what the current `Siibra` class name might better be. For instance it could be something like `session`, so then the initial call to constructor would be 
`>> sibra.session()`

A typical MATLAB pattern is to define an `+internal` sub-package in the root package, to hide away classes not directly interacted with by the user. In this case, likely the `NeuroglancerAdapter` would move into the `+internal` sub-package.

**Comment by vijayiyer05** [comment]
The use of `getXXX` methods for property access is not common in MATLAB usage. I would say it's not recommended. 

Direct access (getting and setting) of property values is possible via [property access methods|https://www.mathworks.com/help/matlab/matlab_oop/property-access-methods.html#:~:text=Property%20access%20methods%20execute%20specific,range%20restrictions%20(Validate%20Property%20Values)] defined for each of the class properties.

**Comment by vijayiyer05** [comment]
@valentin-pinkau Standing ready to mark this closed pending the merge of #24.
If any merge issues arise with upstream team, please keep me posted.

**Comment by valentin-pinkau** [comment]
@vijayiyer05 So this can be closed now?
